AllCops:
  Exclude:
    - Gemfile
  DisplayCopNames: true
AmbiguousOperator:
  Enabled: false
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/IndentHash:
  EnforcedStyle: consistent
Style/LambdaCall:
  Enabled: false
Style/MultilineMethodCallIndentation:
  Enabled: false
Style/Next:
  Enabled: false
Style/WordArray:
  Enabled: false
AmbiguousOperator:
  Enabled: false
Style/ModuleFunction:
  EnforcedStyle: extend_self
